name: food_seller
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  # --- Core ---
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  dartz: ^0.10.1
  get_it: ^8.0.3
  intl: ^0.20.2 # نسخه جدیدتر

  # --- State Management ---
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1

  # --- Networking ---
  supabase_flutter: ^2.9.1
  dio: ^5.8.0+1

  # --- UI/UX ---
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1

  # --- Map & Location ---
  geolocator: ^12.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

  image_picker: ^1.2.0
  mime: ^1.0.5
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/logo/logo1.jpg

  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazirmatn-Thin.ttf
          weight: 100
        - asset: assets/fonts/Vazirmatn-Light.ttf
          weight: 300
        - asset: assets/fonts/Vazirmatn-Medium.ttf
          weight: 500
        - asset: assets/fonts/Vazirmatn-Bold.ttf
          weight: 700

# ⚙️ تنظیمات flutter_launcher_icons باید در ریشه‌ی فایل باشد نه داخل flutter:
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo1.jpg"
  adaptive_icon_background: "#E74C3C"
  adaptive_icon_foreground: "assets/logo/logo1.jpg"
